web development course
citec-47/capston-project pull request #1
Opened 2023-03-15 05:58 UTC by citec-47

**WEB DEVELOPMENT COURSE**

2023-03-15 17:28 UTC, DuaneDave requested changes
Hi @citec-47 👋 , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!



## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you consider them as they can improve your code._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-15 17:28 UTC, DuaneDave commented on index.html
> +</footer>
It is fundamental to stick with the proposed color as provided in the template, the color on the footer is expected to white on the homepage and dark on the about page. Please implement the footer as a white background section on the homepage in order to stick to the provided template

2023-03-15 17:28 UTC, DuaneDave commented on index.html
> +            </div>
Good design with the courses section 👍, however there are some slight improvements to make in order to keep in sync with the project requirements. 

- the underline design underneath the section header is not present in your design
- on hover on the cards, the color of the border is white and not pink.
- the alignment of the courses icon

YOUR VERSION

![urs](https://user-images.githubusercontent.com/84930355/225367833-75f3c027-1370-4fc1-965d-08bb8baebf07.PNG)


BEHANCE DESIGN

![nt good](https://user-images.githubusercontent.com/84930355/225367231-13bcdb26-4529-43ef-9b06-6a14cb1eb788.PNG)

Do not forget that the [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md#:~:text=You%20should%20follow,space%20between%20elements.) put strict adherence to color, layout compositions and spacings.

2023-03-15 17:28 UTC, DuaneDave commented on index.html
> +                <h1 class="codes-name">Javascript</h1>
To provide better seo ranking and accessibility, i recommend making this heading and `h3` tag instead of an `h1` tag

2023-03-15 17:28 UTC, DuaneDave commented on index.html
> +            <h5>@ National Museum of Korea, Art center Nabi and more</h5>
Good job working on this section however, there are couple of adjustments that must be made to spacings, font sizes and the usage of the heading tags here in order to provide an attractive UI, a well ranked website and better accessibility.

Please consider the following 👍 
- The alignment of all the texts are to the left and they are well aligned with the logo aas seen in the behance version, but your design is not following that sort of arrangements
- The `h3` tag should be an `h1` tag since a page will always start with the highest heading and this will help web crawlers see the page properly when ranking
- The first `h2` tag should at least be a `p` tag as it is not proper to start a page with a lower heading as compared to other sections for better accessibity
- The font sizes for the date and venue are looking quite smaller than expected.
- The width of the `div` with class of `boundry` is too wide when compared with the behance version. i suggest you adress this in order to get rid of the too much white spaces around the texts.
- Please pay attention to the color difference between the color of the `Hello! Sharing World` text for your version and the behance version. (Behance version is not a dark text but yours is dark).
- Lastly, please allow the `World Top Programming Languages` text take more spaces as seen in the behance version to not make it too squished up.

BEHANCE VERSION

![align](https://user-images.githubusercontent.com/84930355/225374484-80f58289-ae19-45fd-88db-c07dd0d62502.PNG)


YOUR VERSION

![BSADALIGN](https://user-images.githubusercontent.com/84930355/225375253-04f410e6-3135-49fc-8fb2-30a475424bdd.PNG)

2023-03-15 17:28 UTC, DuaneDave commented on script.js
> +  sonImage.classList = 'son_img';
Great job rendering this content dynamically. However, there are couple of thinfgs I think is left out:

- the underline decoration for the section heading is missing in your version
- the alignment of the lecturer's card is quite different from that of the behance version

YOUR VERSION

![noPropr](https://user-images.githubusercontent.com/84930355/225378821-8566afbd-d0bc-4bd6-b978-c3df3be2baf9.PNG)


BEHANCE VERSION

![proper](https://user-images.githubusercontent.com/84930355/225378915-4ce89067-e492-4bad-80fc-17e227038f3a.PNG)


I recommend addressing the above-mentioned issue in order to have a design similar to that of the behance and to remove excessive white spaces in the website.

2023-03-15 17:28 UTC, DuaneDave commented on about.html
> +                    </ul>
Good job implementing your own idea in this part of the about page. But do not forget that you are required to only change the contents and not the page layouts and composition. So i recommend:

- Making this section similar to the provided template on behance having a centered column that includes a page title, a text block with the page description, and a line with a contact information or any other prompt under it.

Note: if you want to keep your design, that is totally fine but do make sure that you have the same structure of things as in behance and your design idea will be additions.
- Consider using the correct background color for this section too as seen in behance


BEHANCE VERSION

![lol](https://user-images.githubusercontent.com/84930355/225382654-de249f4e-6fe7-4fed-a87d-e5b7808ce71c.PNG)

Addressing all these issues will not only make your website match the original design, but much more make it up to date with the approach of popular websites, since the about page always contains details of the company or the vision and ideology they have.

2023-03-15 17:28 UTC, DuaneDave commented on about.html
> +    <footer>
According to the design, before the footer, there should exist two sections that has:

- A header with a decorative underline plus a paragraph of text, and an image or large logo. see below

![bbbbbad](https://user-images.githubusercontent.com/84930355/225390368-617d6b1e-7ebb-498f-aa68-dfda0d98c37f.PNG)

- a section with a centered column that includes a section header, a divider, a line of text, and two images with text centered over them. see the image below

![Am](https://user-images.githubusercontent.com/84930355/225391243-0a899127-259c-42b5-a13b-e95d0efc1b50.PNG)

Kindly address all the above mentioned to make your design similar to that of the behance version

2023-03-17 10:50 UTC, Owusu-Desmond requested changes
Hi @citec-47 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/h7u3pLvYK3HfQ4yXxW/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 10:50 UTC, Owusu-Desmond commented on index.html
>          <h1 class="het">Creative Commons Global Submit 2015</h1>
- [ ] While working on the requested changes by the previous reviewer, However, your background image and background design are not showing as it is in [Cindy's design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015).

  ### Your Design
  ![Screenshot from 2023-03-17 10-21-06](https://user-images.githubusercontent.com/92303891/225881004-cbb28f84-84f1-44e3-9673-55638f6fc6ef.png)

   ### Cindys design
   
  ![image](https://user-images.githubusercontent.com/92303891/225881619-bc90360b-c448-474a-9c72-62b7eeb2b656.png)

2023-03-17 10:50 UTC, Owusu-Desmond commented on README.md
> +- Watch🙏(https://www.loom.com/share/5cca07fe06174baab741632c0fedf1a9)
- [ OPTIONAL ] Please make sure that you give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/). :pray:

2023-03-17 11:58 UTC, Shedrack-Sunday approved these changes
Hi @citec-47 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)

# Highlights
- No linter errors ✔️
- Good implementations ✔️


## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

- [ ] As suggested by the previous reviewer, kindly include the links and proper acknowledgment as stated on the project requirements 

## Instructions:
![image](https://user-images.githubusercontent.com/50990925/225897553-2792887d-5dd4-466e-88e4-78152bc59f15.png)


__check the comments for details

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-17 11:58 UTC, Shedrack-Sunday commented on README.md
>  - I would like to thank microverse for their amazing school program
- [Optional] Though you did add a a normal message, kindly include the links to give proper acknowledgment 
- E.g

Original design idea by [Cindy Shin in Behance](https://www.behance.net/adagio07).

-  Therefore, please add it to the README of your project.

2023-03-17 12:06 UTC, merged